-- 0002 node transport / TLS / Reality fields (PostgreSQL)
ALTER TABLE nodes
  ADD COLUMN IF NOT EXISTS ws_path TEXT NOT NULL DEFAULT '/',
  ADD COLUMN IF NOT EXISTS ws_host TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS grpc_service_name TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS sni TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS fingerprint TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS reality_public_key TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS reality_short_id TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS reality_server_name TEXT NOT NULL DEFAULT '';
