-- 0003 protocol-hardening fields (PostgreSQL)
ALTER TABLE nodes
  ADD COLUMN IF NOT EXISTS flow TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS alpn TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS mux_enabled SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ss_method TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS reality_private_key TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS reality_dest TEXT NOT NULL DEFAULT '';
