-- 0004 hysteria2 / tuic fields (PostgreSQL)
ALTER TABLE nodes
  ADD COLUMN IF NOT EXISTS obfs_password TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS congestion_control TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS up_mbps INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS down_mbps INTEGER NOT NULL DEFAULT 0;
