ALTER TABLE plans ADD COLUMN quarterly_price NUMERIC(18,2) NOT NULL DEFAULT 0;
ALTER TABLE plans ADD COLUMN yearly_price NUMERIC(18,2) NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN plan_period TEXT NOT NULL DEFAULT 'monthly';
ALTER TABLE orders ADD COLUMN billing_period TEXT NOT NULL DEFAULT 'monthly';
ALTER TABLE orders ADD COLUMN original_amount NUMERIC(18,2) NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN credit_amount NUMERIC(18,2) NOT NULL DEFAULT 0;
