-- 0003 protocol-hardening fields (SQLite)
ALTER TABLE nodes ADD COLUMN flow TEXT NOT NULL DEFAULT '';
ALTER TABLE nodes ADD COLUMN alpn TEXT NOT NULL DEFAULT '';
ALTER TABLE nodes ADD COLUMN mux_enabled INTEGER NOT NULL DEFAULT 0;
ALTER TABLE nodes ADD COLUMN ss_method TEXT NOT NULL DEFAULT '';
ALTER TABLE nodes ADD COLUMN reality_private_key TEXT NOT NULL DEFAULT '';
ALTER TABLE nodes ADD COLUMN reality_dest TEXT NOT NULL DEFAULT '';
