ALTER TABLE plans ADD COLUMN quarterly_price TEXT NOT NULL DEFAULT '0.00';
ALTER TABLE plans ADD COLUMN yearly_price TEXT NOT NULL DEFAULT '0.00';
ALTER TABLE users ADD COLUMN plan_period TEXT NOT NULL DEFAULT 'monthly';
ALTER TABLE orders ADD COLUMN billing_period TEXT NOT NULL DEFAULT 'monthly';
ALTER TABLE orders ADD COLUMN original_amount TEXT NOT NULL DEFAULT '0.00';
ALTER TABLE orders ADD COLUMN credit_amount TEXT NOT NULL DEFAULT '0.00';
