-- 0003 protocol-hardening fields (MySQL / MariaDB)
ALTER TABLE nodes
  ADD COLUMN flow VARCHAR(64) NOT NULL DEFAULT '',
  ADD COLUMN alpn VARCHAR(128) NOT NULL DEFAULT '',
  ADD COLUMN mux_enabled TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN ss_method VARCHAR(64) NOT NULL DEFAULT '',
  ADD COLUMN reality_private_key VARCHAR(128) NOT NULL DEFAULT '',
  ADD COLUMN reality_dest VARCHAR(255) NOT NULL DEFAULT '';
