-- 0011 key-value application settings (MySQL / MariaDB)
CREATE TABLE IF NOT EXISTS app_settings (
  `key` VARCHAR(128) PRIMARY KEY,
  `value` TEXT NOT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
