ALTER TABLE plans ADD COLUMN quarterly_price DECIMAL(18,2) NOT NULL DEFAULT 0;
ALTER TABLE plans ADD COLUMN yearly_price DECIMAL(18,2) NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN plan_period VARCHAR(32) NOT NULL DEFAULT 'monthly';
ALTER TABLE orders ADD COLUMN billing_period VARCHAR(32) NOT NULL DEFAULT 'monthly';
ALTER TABLE orders ADD COLUMN original_amount DECIMAL(18,2) NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN credit_amount DECIMAL(18,2) NOT NULL DEFAULT 0;
